language: node_js
node_js:
- '7'
- '6'
- '4'
script:
- npm run lint
- npm run build
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true
  on:
    tags: true
    repo: mariotacke/color-thief